services:
    app:
        hostname: app01
        container_name: app01
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - .:/app
        ports:
            - "3000:3000"
        command: pnpm run dev
        networks:
            - legendary-spoon_ff_net
        deploy:
            resources:
                limits:
                    cpus: "0.95"
                    memory: "4GB"

networks:
    legendary-spoon_ff_net:
        external: true
